// AUTO-GENERATED by .perf/gen-uht.mjs — the field-id contract for the Ultrasonic
// Hatch Testing template. The ids are FIXED and must match the seed migration
// (072_ultrasonic_hatch_testing.sql) and the live data.
//
// Migration 109 collapsed the original four test sections (Initial + Re-test 1/2/3)
// into ONE repeatable "Test round" section, so rounds are now INSTANCES of this
// single field set: instance 0 is the initial test, 1+ are re-tests (encoded
// `${fieldId}@@${n}`). Migration 112 split the single bilges field into Bilge 1..9
// (one per hold, billed per bilge). The email generator (./email.ts) reads
// job_field_values by these ids across instances, so renaming a LABEL is safe.

export const UHT_TEMPLATE_ID = '75480000-0000-4000-8000-000000000001'

export interface UhtRound {
  date: string
  start: string
  end: string
  holds: string[]        // 9 pass_fail field ids, Hold 1..9
  bilges: string[]       // 9 pass_fail field ids, Bilge 1..9 (one per hold)
  retestRequired: string | null
}

export const UHT_DETAILS = {
  location: '75480000-0000-4000-8000-000000000003',
  holds: '75480000-0000-4000-8000-000000000004',
  hatches: '75480000-0000-4000-8000-000000000005',
} as const

// One round, repeated per job (instance 0 = initial test, 1+ = re-tests).
export const UHT_ROUND: UhtRound = {
  date: '75480000-0000-4000-8000-000000000007',
  start: '75480000-0000-4000-8000-000000000008',
  end: '75480000-0000-4000-8000-000000000009',
  holds: [
    '75480000-0000-4000-8000-000000000010',
    '75480000-0000-4000-8000-000000000011',
    '75480000-0000-4000-8000-000000000012',
    '75480000-0000-4000-8000-000000000013',
    '75480000-0000-4000-8000-000000000014',
    '75480000-0000-4000-8000-000000000015',
    '75480000-0000-4000-8000-000000000016',
    '75480000-0000-4000-8000-000000000017',
    '75480000-0000-4000-8000-000000000018'
  ],
  bilges: [
    '75480000-0000-4000-8000-000000000019',
    '75480000-0000-4000-8000-000000000065',
    '75480000-0000-4000-8000-000000000066',
    '75480000-0000-4000-8000-000000000067',
    '75480000-0000-4000-8000-000000000068',
    '75480000-0000-4000-8000-000000000069',
    '75480000-0000-4000-8000-000000000070',
    '75480000-0000-4000-8000-000000000071',
    '75480000-0000-4000-8000-000000000072'
  ],
  retestRequired: '75480000-0000-4000-8000-000000000020'
}
