-- ============================================================
-- Migration 072: Ultrasonic Hatch Testing template (+ job type + cargo link column)
-- Run in Supabase SQL Editor or via the db-migrate runner. Idempotent.
--
-- Seeds a standard checklist template with FIXED field ids (prefix 75480000-…) so
-- the email generator (src/lib/uht/email.ts via src/lib/uht/fields.ts) has a stable
-- contract independent of field labels. Vessel + client come from the JOB record.
-- AUTO-GENERATED by .perf/gen-uht.mjs — do not hand-edit ids.
-- ============================================================

-- Soft, nullable link to a cargo-monitoring voyage (string ref; hardens to FK later).
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS cargo_voyage_ref TEXT;

-- Tracker job-type filter.
INSERT INTO public.job_types (name)
  SELECT 'Ultrasonic Hatch Testing'
  WHERE NOT EXISTS (SELECT 1 FROM public.job_types WHERE name = 'Ultrasonic Hatch Testing');

-- Template (created_by = an active admin, falling back to any profile).
INSERT INTO public.checklist_templates (id, name, description, status, allow_surveyor_start, created_by)
SELECT '75480000-0000-4000-8000-000000000001', 'Ultrasonic Hatch Testing',
       'Ultrasonic hatch (weathertightness) testing of bulk-carrier holds/hatches. Records each visit''s date + times (billing) and per-hold pass/fail; generates the email summary.',
       'active'::template_status, true,
       COALESCE((SELECT id FROM public.profiles WHERE role = 'admin' AND is_active ORDER BY created_at LIMIT 1),
                (SELECT id FROM public.profiles ORDER BY created_at LIMIT 1))
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.template_sections (id, template_id, title, order_index, conditional_logic) VALUES
  ('75480000-0000-4000-8000-000000000002','75480000-0000-4000-8000-000000000001','Job details',0,null),
  ('75480000-0000-4000-8000-000000000006','75480000-0000-4000-8000-000000000001','Initial test',1,null),
  ('75480000-0000-4000-8000-000000000021','75480000-0000-4000-8000-000000000001','Re-test 1',2,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000020","operator":"equals","value":"yes"}]}'::jsonb),
  ('75480000-0000-4000-8000-000000000036','75480000-0000-4000-8000-000000000001','Re-test 2',3,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000035","operator":"equals","value":"yes"}]}'::jsonb),
  ('75480000-0000-4000-8000-000000000051','75480000-0000-4000-8000-000000000001','Re-test 3',4,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000050","operator":"equals","value":"yes"}]}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.template_fields (id, template_id, section_id, label, field_type, order_index, is_required, validation, conditional_logic, default_value) VALUES
  ('75480000-0000-4000-8000-000000000003','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000002','Location','text',0,false,null,null,'Point Lisas anchorage'),
  ('75480000-0000-4000-8000-000000000004','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000002','Number of holds','number',1,false,'{"min":1,"max":9}'::jsonb,null,null),
  ('75480000-0000-4000-8000-000000000005','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000002','Number of hatches','number',2,false,'{"min":1,"max":9}'::jsonb,null,null),
  ('75480000-0000-4000-8000-000000000007','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000006','Date','date',0,true,null,null,null),
  ('75480000-0000-4000-8000-000000000008','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000006','Start time','time',1,true,null,null,null),
  ('75480000-0000-4000-8000-000000000009','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000006','End time','time',2,true,null,null,null),
  ('75480000-0000-4000-8000-000000000010','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000006','Hold 1','yes_no',3,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"0"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000011','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000006','Hold 2','yes_no',4,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"1"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000012','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000006','Hold 3','yes_no',5,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"2"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000013','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000006','Hold 4','yes_no',6,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"3"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000014','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000006','Hold 5','yes_no',7,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"4"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000015','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000006','Hold 6','yes_no',8,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"5"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000016','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000006','Hold 7','yes_no',9,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"6"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000017','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000006','Hold 8','yes_no',10,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"7"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000018','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000006','Hold 9','yes_no',11,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"8"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000019','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000006','Bilges clean & dry','yes_no',12,false,null,null,null),
  ('75480000-0000-4000-8000-000000000020','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000006','Further re-test required?','yes_no',13,false,null,null,null),
  ('75480000-0000-4000-8000-000000000022','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000021','Date','date',0,false,null,null,null),
  ('75480000-0000-4000-8000-000000000023','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000021','Start time','time',1,false,null,null,null),
  ('75480000-0000-4000-8000-000000000024','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000021','End time','time',2,false,null,null,null),
  ('75480000-0000-4000-8000-000000000025','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000021','Hold 1','yes_no',3,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"0"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000026','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000021','Hold 2','yes_no',4,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"1"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000027','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000021','Hold 3','yes_no',5,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"2"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000028','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000021','Hold 4','yes_no',6,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"3"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000029','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000021','Hold 5','yes_no',7,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"4"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000030','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000021','Hold 6','yes_no',8,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"5"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000031','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000021','Hold 7','yes_no',9,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"6"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000032','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000021','Hold 8','yes_no',10,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"7"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000033','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000021','Hold 9','yes_no',11,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"8"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000034','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000021','Bilges clean & dry','yes_no',12,false,null,null,null),
  ('75480000-0000-4000-8000-000000000035','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000021','Further re-test required?','yes_no',13,false,null,null,null),
  ('75480000-0000-4000-8000-000000000037','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000036','Date','date',0,false,null,null,null),
  ('75480000-0000-4000-8000-000000000038','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000036','Start time','time',1,false,null,null,null),
  ('75480000-0000-4000-8000-000000000039','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000036','End time','time',2,false,null,null,null),
  ('75480000-0000-4000-8000-000000000040','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000036','Hold 1','yes_no',3,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"0"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000041','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000036','Hold 2','yes_no',4,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"1"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000042','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000036','Hold 3','yes_no',5,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"2"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000043','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000036','Hold 4','yes_no',6,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"3"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000044','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000036','Hold 5','yes_no',7,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"4"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000045','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000036','Hold 6','yes_no',8,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"5"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000046','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000036','Hold 7','yes_no',9,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"6"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000047','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000036','Hold 8','yes_no',10,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"7"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000048','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000036','Hold 9','yes_no',11,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"8"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000049','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000036','Bilges clean & dry','yes_no',12,false,null,null,null),
  ('75480000-0000-4000-8000-000000000050','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000036','Further re-test required?','yes_no',13,false,null,null,null),
  ('75480000-0000-4000-8000-000000000052','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000051','Date','date',0,false,null,null,null),
  ('75480000-0000-4000-8000-000000000053','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000051','Start time','time',1,false,null,null,null),
  ('75480000-0000-4000-8000-000000000054','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000051','End time','time',2,false,null,null,null),
  ('75480000-0000-4000-8000-000000000055','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000051','Hold 1','yes_no',3,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"0"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000056','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000051','Hold 2','yes_no',4,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"1"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000057','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000051','Hold 3','yes_no',5,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"2"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000058','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000051','Hold 4','yes_no',6,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"3"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000059','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000051','Hold 5','yes_no',7,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"4"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000060','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000051','Hold 6','yes_no',8,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"5"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000061','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000051','Hold 7','yes_no',9,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"6"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000062','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000051','Hold 8','yes_no',10,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"7"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000063','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000051','Hold 9','yes_no',11,false,null,'{"operator":"and","conditions":[{"field_id":"75480000-0000-4000-8000-000000000004","operator":"greater_than","value":"8"}]}'::jsonb,null),
  ('75480000-0000-4000-8000-000000000064','75480000-0000-4000-8000-000000000001','75480000-0000-4000-8000-000000000051','Bilges clean & dry','yes_no',12,false,null,null,null)
ON CONFLICT (id) DO NOTHING;
